packages:
  - "ace"
  - "adv-danmaku"
  - "as3-danmaku"
  - "audio-effect"
  - "b-*"
  - "bilibiliplayer"
  - "combo"
  - "danmaku"
  - "dash-player"
  - "drm"
  - "event-log"
  - "flv.js"
  - "must-h5"
  - "namespace"
  - "no-flash-tips"
  - "pbploader"
  - "player-auxiliary"
  - "playurl"
  - "qrcode"
  - "screenshot"
  - "speed-tester"
  - "websocket-broadcast"
  - "shared"