import { writeFileSync, readFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const version = JSON.parse(readFileSync(resolve(__dirname, '../package.json'), 'utf-8')).version;
let revision = 'unknown';
try {
	revision = execSync('git rev-parse --short HEAD', { encoding: 'utf-8' }).trim();
} catch (e) {
	console.warn('⚠️  Git not available, using "unknown" for revision.');
}
const lastCompiled = new Date().toISOString();

const content = `// Auto-generated by scripts/metadata.mjs. DO NOT EDIT.
export const METADATA = {
\tversion: "${version}",
\trevision: "${revision}",
\tlastCompiled: "${lastCompiled}"
} as const;`;

const outputPath = resolve(__dirname, '../namespace/metadata.ts');
writeFileSync(outputPath, content, 'utf-8');
console.log(`✅ METADATA written to: ${outputPath}`);
console.log(`   Revision: ${revision}`);
console.log(`   Compiled: ${lastCompiled}`);